### ISSUE TITLE
datasets do not contain s->o + o->s links

### ISSUE THREAD

**Issue by vmcj** [shuaiwangvu/sameaseq_data#1]
When checking the resulting graphs I think there is never a graph where s->o and also o->s,

Is this correct?

**Comment by shuaiwangvu** [comment]
Well, there can be. Maybe just not in these samples retrieved. 

Generally speaking, owl:sameAs is an equivalence relation. So s->o means s=o. Thus the meaning won't change with or without another statement o->s. 

I will try my best to give you my annotation as soon as possible (hopefully by Friday) so you can evaluate your work.

Sorry about the delay. I was very sick last week.

**Comment by vmcj** [comment]
I verified in other ways and indeed this is the case, I'll close the issue.

**Comment by shuaiwangvu** [comment]
Hi @mvr320. I uploaded some annotated data. Please let me know if you see any problem. Thanks. 
I will further verify the annotation this weekend.

**Comment by vmcj** [comment]
Hi @shuaiwangvu I'll check them but what I can see from the notes it makes sense.
